# Generated by Django 4.2.1 on 2023-05-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='#000000', max_length=50),
            preserve_default=False,
        ),
    ]
